# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:/Users/Bryan Taylor/Documents/ui/tadokutan_scores.ui'
#
# Created: Sat Jun 02 13:43:50 2012
#      by: PyQt4 UI code generator 4.9.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
	_fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
	_fromUtf8 = lambda s: s

class Ui_ScoresDlg(object):
	def setupUi(self, ScoresDlg):
		ScoresDlg.setObjectName(_fromUtf8("ScoresDlg"))
		ScoresDlg.resize(400, 260)
		self.buttonBox = QtGui.QDialogButtonBox(ScoresDlg)
		self.buttonBox.setGeometry(QtCore.QRect(30, 220, 341, 32))
		self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
		self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Ok)
		self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
		self.groupBox = QtGui.QGroupBox(ScoresDlg)
		self.groupBox.setGeometry(QtCore.QRect(20, 10, 161, 241))
		self.groupBox.setObjectName(_fromUtf8("groupBox"))
		self.booklb = QtGui.QLabel(self.groupBox)
		self.booklb.setGeometry(QtCore.QRect(10, 20, 81, 16))
		self.booklb.setObjectName(_fromUtf8("booklb"))
		self.bookdrlb = QtGui.QLabel(self.groupBox)
		self.bookdrlb.setGeometry(QtCore.QRect(10, 40, 101, 16))
		self.bookdrlb.setObjectName(_fromUtf8("bookdrlb"))
		self.mangalb = QtGui.QLabel(self.groupBox)
		self.mangalb.setGeometry(QtCore.QRect(10, 60, 71, 16))
		self.mangalb.setObjectName(_fromUtf8("mangalb"))
		self.flgamelb = QtGui.QLabel(self.groupBox)
		self.flgamelb.setGeometry(QtCore.QRect(10, 100, 111, 16))
		self.flgamelb.setObjectName(_fromUtf8("flgamelb"))
		self.gamelb = QtGui.QLabel(self.groupBox)
		self.gamelb.setGeometry(QtCore.QRect(10, 120, 101, 16))
		self.gamelb.setObjectName(_fromUtf8("gamelb"))
		self.netlb = QtGui.QLabel(self.groupBox)
		self.netlb.setGeometry(QtCore.QRect(10, 140, 91, 16))
		self.netlb.setObjectName(_fromUtf8("netlb"))
		self.newslb = QtGui.QLabel(self.groupBox)
		self.newslb.setGeometry(QtCore.QRect(10, 160, 101, 16))
		self.newslb.setObjectName(_fromUtf8("newslb"))
		self.nicolb = QtGui.QLabel(self.groupBox)
		self.nicolb.setGeometry(QtCore.QRect(10, 180, 91, 16))
		self.nicolb.setObjectName(_fromUtf8("nicolb"))
		self.subslb = QtGui.QLabel(self.groupBox)
		self.subslb.setGeometry(QtCore.QRect(10, 200, 101, 16))
		self.subslb.setObjectName(_fromUtf8("subslb"))
		self.sentlb = QtGui.QLabel(self.groupBox)
		self.sentlb.setGeometry(QtCore.QRect(10, 220, 101, 16))
		self.sentlb.setObjectName(_fromUtf8("sentlb"))
		self.book_score = QtGui.QLabel(self.groupBox)
		self.book_score.setGeometry(QtCore.QRect(50, 20, 101, 16))
		self.book_score.setLayoutDirection(QtCore.Qt.LeftToRight)
		self.book_score.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
		self.book_score.setObjectName(_fromUtf8("book_score"))
		self.bookdr_score = QtGui.QLabel(self.groupBox)
		self.bookdr_score.setGeometry(QtCore.QRect(50, 40, 101, 16))
		self.bookdr_score.setLayoutDirection(QtCore.Qt.LeftToRight)
		self.bookdr_score.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
		self.bookdr_score.setObjectName(_fromUtf8("bookdr_score"))
		self.manga_score = QtGui.QLabel(self.groupBox)
		self.manga_score.setGeometry(QtCore.QRect(50, 60, 101, 16))
		self.manga_score.setLayoutDirection(QtCore.Qt.LeftToRight)
		self.manga_score.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
		self.manga_score.setObjectName(_fromUtf8("manga_score"))
		self.flgame_score = QtGui.QLabel(self.groupBox)
		self.flgame_score.setGeometry(QtCore.QRect(50, 100, 101, 16))
		self.flgame_score.setLayoutDirection(QtCore.Qt.LeftToRight)
		self.flgame_score.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
		self.flgame_score.setObjectName(_fromUtf8("flgame_score"))
		self.game_score = QtGui.QLabel(self.groupBox)
		self.game_score.setGeometry(QtCore.QRect(50, 120, 101, 16))
		self.game_score.setLayoutDirection(QtCore.Qt.LeftToRight)
		self.game_score.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
		self.game_score.setObjectName(_fromUtf8("game_score"))
		self.net_score = QtGui.QLabel(self.groupBox)
		self.net_score.setGeometry(QtCore.QRect(50, 140, 101, 16))
		self.net_score.setLayoutDirection(QtCore.Qt.LeftToRight)
		self.net_score.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
		self.net_score.setObjectName(_fromUtf8("net_score"))
		self.news_score = QtGui.QLabel(self.groupBox)
		self.news_score.setGeometry(QtCore.QRect(50, 160, 101, 16))
		self.news_score.setLayoutDirection(QtCore.Qt.LeftToRight)
		self.news_score.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
		self.news_score.setObjectName(_fromUtf8("news_score"))
		self.nico_score = QtGui.QLabel(self.groupBox)
		self.nico_score.setGeometry(QtCore.QRect(50, 180, 101, 16))
		self.nico_score.setLayoutDirection(QtCore.Qt.LeftToRight)
		self.nico_score.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
		self.nico_score.setObjectName(_fromUtf8("nico_score"))
		self.subs_score = QtGui.QLabel(self.groupBox)
		self.subs_score.setGeometry(QtCore.QRect(50, 200, 101, 16))
		self.subs_score.setLayoutDirection(QtCore.Qt.LeftToRight)
		self.subs_score.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
		self.subs_score.setObjectName(_fromUtf8("subs_score"))
		self.sent_score = QtGui.QLabel(self.groupBox)
		self.sent_score.setGeometry(QtCore.QRect(50, 220, 101, 16))
		self.sent_score.setLayoutDirection(QtCore.Qt.LeftToRight)
		self.sent_score.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
		self.sent_score.setObjectName(_fromUtf8("sent_score"))
		self.lyriclb = QtGui.QLabel(self.groupBox)
		self.lyriclb.setGeometry(QtCore.QRect(10, 80, 81, 16))
		self.lyriclb.setObjectName(_fromUtf8("lyriclb"))
		self.lyric_score = QtGui.QLabel(self.groupBox)
		self.lyric_score.setGeometry(QtCore.QRect(50, 80, 101, 16))
		self.lyric_score.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
		self.lyric_score.setObjectName(_fromUtf8("lyric_score"))
		self.totallb = QtGui.QLabel(ScoresDlg)
		self.totallb.setGeometry(QtCore.QRect(200, 10, 121, 16))
		self.totallb.setObjectName(_fromUtf8("totallb"))
		self.total_score = QtGui.QLabel(ScoresDlg)
		self.total_score.setGeometry(QtCore.QRect(200, 30, 191, 16))
		self.total_score.setObjectName(_fromUtf8("total_score"))
		self.values_radio = QtGui.QRadioButton(ScoresDlg)
		self.values_radio.setGeometry(QtCore.QRect(200, 210, 82, 17))
		self.values_radio.setObjectName(_fromUtf8("values_radio"))
		self.buttonGroup = QtGui.QButtonGroup(ScoresDlg)
		self.buttonGroup.setObjectName(_fromUtf8("buttonGroup"))
		self.buttonGroup.addButton(self.values_radio)
		self.scores_radio = QtGui.QRadioButton(ScoresDlg)
		self.scores_radio.setGeometry(QtCore.QRect(200, 190, 82, 17))
		self.scores_radio.setChecked(True)
		self.scores_radio.setObjectName(_fromUtf8("scores_radio"))
		self.buttonGroup.addButton(self.scores_radio)

		self.retranslateUi(ScoresDlg)
		QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), ScoresDlg.accept)
		QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), ScoresDlg.reject)
		QtCore.QMetaObject.connectSlotsByName(ScoresDlg)

	def retranslateUi(self, ScoresDlg):
		ScoresDlg.setWindowTitle(QtGui.QApplication.translate("ScoresDlg", "Scores", None, QtGui.QApplication.UnicodeUTF8))
		self.groupBox.setTitle(QtGui.QApplication.translate("ScoresDlg", "Score Breakdown", None, QtGui.QApplication.UnicodeUTF8))
		self.booklb.setText(QtGui.QApplication.translate("ScoresDlg", "Book:", None, QtGui.QApplication.UnicodeUTF8))
		self.bookdrlb.setText(QtGui.QApplication.translate("ScoresDlg", "Book, DR:", None, QtGui.QApplication.UnicodeUTF8))
		self.mangalb.setText(QtGui.QApplication.translate("ScoresDlg", "Manga:", None, QtGui.QApplication.UnicodeUTF8))
		self.flgamelb.setText(QtGui.QApplication.translate("ScoresDlg", "Full Game:", None, QtGui.QApplication.UnicodeUTF8))
		self.gamelb.setText(QtGui.QApplication.translate("ScoresDlg", "Game:", None, QtGui.QApplication.UnicodeUTF8))
		self.netlb.setText(QtGui.QApplication.translate("ScoresDlg", "Net:", None, QtGui.QApplication.UnicodeUTF8))
		self.newslb.setText(QtGui.QApplication.translate("ScoresDlg", "News:", None, QtGui.QApplication.UnicodeUTF8))
		self.nicolb.setText(QtGui.QApplication.translate("ScoresDlg", "NicoNico:", None, QtGui.QApplication.UnicodeUTF8))
		self.subslb.setText(QtGui.QApplication.translate("ScoresDlg", "Subtitles:", None, QtGui.QApplication.UnicodeUTF8))
		self.sentlb.setText(QtGui.QApplication.translate("ScoresDlg", "Sentences:", None, QtGui.QApplication.UnicodeUTF8))
		self.book_score.setText(QtGui.QApplication.translate("ScoresDlg", "0", None, QtGui.QApplication.UnicodeUTF8))
		self.bookdr_score.setText(QtGui.QApplication.translate("ScoresDlg", "0", None, QtGui.QApplication.UnicodeUTF8))
		self.manga_score.setText(QtGui.QApplication.translate("ScoresDlg", "0", None, QtGui.QApplication.UnicodeUTF8))
		self.flgame_score.setText(QtGui.QApplication.translate("ScoresDlg", "0", None, QtGui.QApplication.UnicodeUTF8))
		self.game_score.setText(QtGui.QApplication.translate("ScoresDlg", "0", None, QtGui.QApplication.UnicodeUTF8))
		self.net_score.setText(QtGui.QApplication.translate("ScoresDlg", "0", None, QtGui.QApplication.UnicodeUTF8))
		self.news_score.setText(QtGui.QApplication.translate("ScoresDlg", "0", None, QtGui.QApplication.UnicodeUTF8))
		self.nico_score.setText(QtGui.QApplication.translate("ScoresDlg", "0", None, QtGui.QApplication.UnicodeUTF8))
		self.subs_score.setText(QtGui.QApplication.translate("ScoresDlg", "0", None, QtGui.QApplication.UnicodeUTF8))
		self.sent_score.setText(QtGui.QApplication.translate("ScoresDlg", "0", None, QtGui.QApplication.UnicodeUTF8))
		self.lyriclb.setText(QtGui.QApplication.translate("ScoresDlg", "Lyrics:", None, QtGui.QApplication.UnicodeUTF8))
		self.lyric_score.setText(QtGui.QApplication.translate("ScoresDlg", "0", None, QtGui.QApplication.UnicodeUTF8))
		self.totallb.setText(QtGui.QApplication.translate("ScoresDlg", "Total Score:", None, QtGui.QApplication.UnicodeUTF8))
		self.total_score.setText(QtGui.QApplication.translate("ScoresDlg", "0", None, QtGui.QApplication.UnicodeUTF8))
		self.values_radio.setText(QtGui.QApplication.translate("ScoresDlg", "Values", None, QtGui.QApplication.UnicodeUTF8))
		self.scores_radio.setText(QtGui.QApplication.translate("ScoresDlg", "Scores", None, QtGui.QApplication.UnicodeUTF8))


if __name__ == "__main__":
	import sys
	app = QtGui.QApplication(sys.argv)
	ScoresDlg = QtGui.QDialog()
	ui = Ui_ScoresDlg()
	ui.setupUi(ScoresDlg)
	ScoresDlg.show()
	sys.exit(app.exec_())

